export const SettingKeys = {
  Auth: {
    Enabled: "Auth.Enabled",
    LocalBypassEnabled: "Auth.LocalBypassEnabled",
    LocalBypassCidrs: "Auth.LocalBypassCidrs",
  },
  Agent: {
    // Connection settings
    HeartbeatIntervalSeconds: "Agent.HeartbeatIntervalSeconds",
    MaxReconnectDelaySeconds: "Agent.MaxReconnectDelaySeconds",
    // Telemetry settings
    TelemetryCacheSeconds: "Agent.TelemetryCacheSeconds",
    PrimaryInterfaceName: "Agent.PrimaryInterfaceName",
    EnableNetworkTelemetry: "Agent.EnableNetworkTelemetry",
    EnablePingTelemetry: "Agent.EnablePingTelemetry",
    EnableGpuTelemetry: "Agent.EnableGpuTelemetry",
    EnableUpsTelemetry: "Agent.EnableUpsTelemetry",
    // Enhanced telemetry settings
    EnableEnhancedNetworkTelemetry: "Agent.EnableEnhancedNetworkTelemetry",
    EnableEnhancedGpuTelemetry: "Agent.EnableEnhancedGpuTelemetry",
    EnableApmTelemetry: "Agent.EnableApmTelemetry",
    ApmHealthCheckEndpoints: "Agent.ApmHealthCheckEndpoints",
    ApmDatabaseEndpoints: "Agent.ApmDatabaseEndpoints",
    // Remote tools (security-sensitive)
    EnableLogViewer: "Agent.EnableLogViewer",
    EnableScripts: "Agent.EnableScripts",
    EnableTerminal: "Agent.EnableTerminal",
    EnableFileBrowser: "Agent.EnableFileBrowser",
    // Ping settings
    PingTarget: "Agent.PingTarget",
    PingTimeoutMs: "Agent.PingTimeoutMs",
    PingWindowSize: "Agent.PingWindowSize",
    // Rate limits and bounds
    LogMaxBytes: "Agent.LogMaxBytes",
    LogMinSecondsBetweenRequests: "Agent.LogMinSecondsBetweenRequests",
    ScriptMaxOutputBytes: "Agent.ScriptMaxOutputBytes",
    ScriptMaxDurationSeconds: "Agent.ScriptMaxDurationSeconds",
    ScriptMinSecondsBetweenRuns: "Agent.ScriptMinSecondsBetweenRuns",
    TerminalMaxOutputBytes: "Agent.TerminalMaxOutputBytes",
    TerminalMaxDurationSeconds: "Agent.TerminalMaxDurationSeconds",
    FileBrowserMaxBytes: "Agent.FileBrowserMaxBytes",
    // Agent self-logging settings
    AgentLogFilePath: "Agent.AgentLogFilePath",
    AgentLogFileMaxBytes: "Agent.AgentLogFileMaxBytes",
    AgentLogFileRetainedFiles: "Agent.AgentLogFileRetainedFiles",
  },
  Discord: {
    WebhookUrl: "Discord.WebhookUrl",
  },
  GitHub: {
    EnableGitHubDownload: "GitHub.EnableGitHubDownload",
    ReleaseBaseUrl: "GitHub.ReleaseBaseUrl",
    LatestVersion: "GitHub.LatestVersion",
  },
  Network: {
    RealtimeEnabled: "Network.RealtimeEnabled",
    NotificationsEnabled: "Network.NotificationsEnabled",
    PingHost: "Network.PingHost",
    PingTimeout: "Network.PingTimeout",
    SubnetLast: "Network.SubnetLast",
    SubnetConcurrency: "Network.SubnetConcurrency",
    SubnetTimeout: "Network.SubnetTimeout",
    PortHost: "Network.PortHost",
    PortConcurrency: "Network.PortConcurrency",
    PortTimeout: "Network.PortTimeout",
    TracerouteHost: "Network.TracerouteHost",
    TracerouteMaxHops: "Network.TracerouteMaxHops",
    TracerouteTimeout: "Network.TracerouteTimeout",
    DiscoveryDuration: "Network.DiscoveryDuration",
    DiscoveryMode: "Network.DiscoveryMode",
    WifiAdapter: "Network.WifiAdapter",
    WifiBand: "Network.WifiBand",
    WifiSecurity: "Network.WifiSecurity",
    WolMac: "Network.WolMac",
    WolBroadcast: "Network.WolBroadcast",
    WolPort: "Network.WolPort",
    SpeedtestDownloadMb: "Network.SpeedtestDownloadMb",
    SpeedtestUploadMb: "Network.SpeedtestUploadMb",
    SpeedtestLatencySamples: "Network.SpeedtestLatencySamples",
    TopologyCidr: "Network.TopologyCidr",
    TopologyConcurrency: "Network.TopologyConcurrency",
    TopologyTimeout: "Network.TopologyTimeout",
    TopologyIncludeDiscovery: "Network.TopologyIncludeDiscovery",
    TopologyDiscoveryDuration: "Network.TopologyDiscoveryDuration",
  },
} as const;
