using ManLab.Server.Data.Entities;
using ManLab.Server.Data.Entities.Enhancements;
using Microsoft.EntityFrameworkCore;
using ManLab.Server.Services.Persistence;

namespace ManLab.Server.Data;

/// <summary>
/// Entity Framework Core database context for ManLab.
/// </summary>
public class DataContext : DbContext
{
    public DataContext(DbContextOptions<DataContext> options) : base(options)
    {
    }

    /// <summary>Registered agent nodes.</summary>
    public DbSet<Node> Nodes => Set<Node>();

    /// <summary>Telemetry snapshots from agent nodes.</summary>
    public DbSet<TelemetrySnapshot> TelemetrySnapshots => Set<TelemetrySnapshot>();

    /// <summary>Command queue for async task tracking.</summary>
    public DbSet<CommandQueueItem> CommandQueue => Set<CommandQueueItem>();

    /// <summary>Inventory of machines being onboarded via SSH.</summary>
    public DbSet<OnboardingMachine> OnboardingMachines => Set<OnboardingMachine>();

    /// <summary>Enrollment tokens used to bootstrap agent authentication.</summary>
    public DbSet<EnrollmentToken> EnrollmentTokens => Set<EnrollmentToken>();

    /// <summary>Audit trail for SSH onboarding/provisioning.</summary>
    public DbSet<SshAuditEvent> SshAuditEvents => Set<SshAuditEvent>();

    /// <summary>Activity/audit events generated by the server.</summary>
    public DbSet<AuditEvent> AuditEvents => Set<AuditEvent>();

    /// <summary>System-wide configuration settings.</summary>
    public DbSet<SystemSetting> SystemSettings => Set<SystemSetting>();

    /// <summary>Per-node configuration settings.</summary>
    public DbSet<NodeSetting> NodeSettings => Set<NodeSetting>();

    // Enhancements
    public DbSet<ServiceMonitorConfig> ServiceMonitorConfigs => Set<ServiceMonitorConfig>();
    public DbSet<ServiceStatusSnapshot> ServiceStatusSnapshots => Set<ServiceStatusSnapshot>();
    public DbSet<SmartDriveSnapshot> SmartDriveSnapshots => Set<SmartDriveSnapshot>();
    public DbSet<GpuSnapshot> GpuSnapshots => Set<GpuSnapshot>();
    public DbSet<UpsSnapshot> UpsSnapshots => Set<UpsSnapshot>();

    public DbSet<HttpMonitorConfig> HttpMonitorConfigs => Set<HttpMonitorConfig>();
    public DbSet<HttpMonitorCheck> HttpMonitorChecks => Set<HttpMonitorCheck>();
    public DbSet<TrafficMonitorConfig> TrafficMonitorConfigs => Set<TrafficMonitorConfig>();
    public DbSet<TrafficSample> TrafficSamples => Set<TrafficSample>();

    public DbSet<AlertRule> AlertRules => Set<AlertRule>();
    public DbSet<AlertEvent> AlertEvents => Set<AlertEvent>();

    public DbSet<Script> Scripts => Set<Script>();
    public DbSet<ScriptRun> ScriptRuns => Set<ScriptRun>();

    public DbSet<LogViewerPolicy> LogViewerPolicies => Set<LogViewerPolicy>();
    public DbSet<FileBrowserPolicy> FileBrowserPolicies => Set<FileBrowserPolicy>();
    public DbSet<TerminalSession> TerminalSessions => Set<TerminalSession>();

    /// <summary>Network tool execution history for analytics.</summary>
    public DbSet<NetworkToolHistoryEntry> NetworkToolHistory => Set<NetworkToolHistoryEntry>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Node configuration
        modelBuilder.Entity<Node>(entity =>
        {
            entity.HasIndex(e => e.Hostname);
            entity.HasIndex(e => e.Status);
            entity.HasIndex(e => e.LastSeen);
            entity.HasIndex(e => e.AuthKeyHash);
        });

        // TelemetrySnapshot configuration
        modelBuilder.Entity<TelemetrySnapshot>(entity =>
        {
            entity.HasIndex(e => e.NodeId);
            entity.HasIndex(e => e.Timestamp);
            entity.HasIndex(e => new { e.NodeId, e.Timestamp });

            entity.HasOne(e => e.Node)
                .WithMany(n => n.TelemetrySnapshots)
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // CommandQueueItem configuration
        modelBuilder.Entity<CommandQueueItem>(entity =>
        {
            entity.HasIndex(e => e.NodeId);
            entity.HasIndex(e => e.Status);
            entity.HasIndex(e => e.CreatedAt);
            entity.HasIndex(e => new { e.NodeId, e.CreatedAt });
            entity.HasIndex(e => new { e.NodeId, e.CommandType, e.Status, e.CreatedAt });

            entity.HasOne(e => e.Node)
                .WithMany(n => n.Commands)
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<OnboardingMachine>(entity =>
        {
            entity.HasIndex(e => e.Host);
            entity.HasIndex(e => e.Status);
            entity.HasIndex(e => e.UpdatedAt);
        });

        modelBuilder.Entity<EnrollmentToken>(entity =>
        {
            entity.HasIndex(e => e.TokenHash).IsUnique();
            entity.HasIndex(e => e.ExpiresAt);
            entity.HasIndex(e => e.UsedAt);
            entity.HasIndex(e => e.MachineId);
        });

        modelBuilder.Entity<SshAuditEvent>(entity =>
        {
            entity.HasIndex(e => e.TimestampUtc);
            entity.HasIndex(e => e.Action);
            entity.HasIndex(e => e.MachineId);
            entity.HasIndex(e => e.Host);
            entity.HasIndex(e => e.Success);
        });

        modelBuilder.Entity<AuditEvent>(entity =>
        {
            entity.HasIndex(e => e.TimestampUtc);
            entity.HasIndex(e => e.Kind);
            entity.HasIndex(e => e.EventName);
            entity.HasIndex(e => e.NodeId);
            entity.HasIndex(e => e.CommandId);
            entity.HasIndex(e => e.Success);

            // Store as jsonb for efficient queryability when needed.
            entity.Property(e => e.DataJson).HasColumnType("jsonb");
        });

        modelBuilder.Entity<NodeSetting>(entity =>
        {
            entity.HasKey(e => new { e.NodeId, e.Key });
            entity.HasIndex(e => e.NodeId);

            entity.Property(e => e.Key).HasMaxLength(256);
            entity.Property(e => e.Category).HasMaxLength(64);
            entity.Property(e => e.Description).HasMaxLength(1024);

            entity.HasOne(e => e.Node)
                .WithMany()
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Enhancements: File browser policies
        modelBuilder.Entity<FileBrowserPolicy>(entity =>
        {
            entity.HasIndex(e => e.NodeId);

            entity.HasOne(e => e.Node)
                .WithMany(n => n.FileBrowserPolicies)
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Enhancements: Service monitor config
        modelBuilder.Entity<ServiceMonitorConfig>(entity =>
        {
            entity.HasIndex(e => e.NodeId);
            entity.HasIndex(e => new { e.NodeId, e.ServiceName }).IsUnique();

            entity.HasOne(e => e.Node)
                .WithMany(n => n.ServiceMonitorConfigs)
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Enhancements: Service status snapshots
        modelBuilder.Entity<ServiceStatusSnapshot>(entity =>
        {
            entity.HasIndex(e => e.NodeId);
            entity.HasIndex(e => e.Timestamp);
            entity.HasIndex(e => new { e.NodeId, e.Timestamp });
            entity.HasIndex(e => new { e.NodeId, e.ServiceName, e.Timestamp });
            entity.HasIndex(e => new { e.NodeId, e.Timestamp, e.ServiceName });

            entity.HasOne(e => e.Node)
                .WithMany(n => n.ServiceStatusSnapshots)
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Enhancements: SMART snapshots
        modelBuilder.Entity<SmartDriveSnapshot>(entity =>
        {
            entity.HasIndex(e => e.NodeId);
            entity.HasIndex(e => e.Timestamp);
            entity.HasIndex(e => new { e.NodeId, e.Timestamp });
            entity.HasIndex(e => new { e.NodeId, e.Device, e.Timestamp });
            entity.HasIndex(e => new { e.NodeId, e.Timestamp, e.Device });

            entity.HasOne(e => e.Node)
                .WithMany(n => n.SmartDriveSnapshots)
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Enhancements: GPU snapshots
        modelBuilder.Entity<GpuSnapshot>(entity =>
        {
            entity.HasIndex(e => e.NodeId);
            entity.HasIndex(e => e.Timestamp);
            entity.HasIndex(e => new { e.NodeId, e.Timestamp });
            entity.HasIndex(e => new { e.NodeId, e.GpuIndex, e.Timestamp });
            entity.HasIndex(e => new { e.NodeId, e.Timestamp, e.GpuIndex });

            entity.HasOne(e => e.Node)
                .WithMany(n => n.GpuSnapshots)
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Enhancements: UPS snapshots
        modelBuilder.Entity<UpsSnapshot>(entity =>
        {
            entity.HasIndex(e => e.NodeId);
            entity.HasIndex(e => e.Timestamp);
            entity.HasIndex(e => new { e.NodeId, e.Timestamp });

            entity.HasOne(e => e.Node)
                .WithMany(n => n.UpsSnapshots)
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Monitoring: HTTP monitor configs
        modelBuilder.Entity<HttpMonitorConfig>(entity =>
        {
            entity.HasIndex(e => e.Enabled);
            entity.HasIndex(e => e.UpdatedAt);
            entity.HasIndex(e => e.Url);
        });

        // Monitoring: HTTP monitor checks
        modelBuilder.Entity<HttpMonitorCheck>(entity =>
        {
            entity.HasIndex(e => e.MonitorId);
            entity.HasIndex(e => e.TimestampUtc);
            entity.HasIndex(e => new { e.MonitorId, e.TimestampUtc });
            entity.HasIndex(e => new { e.MonitorId, e.Success, e.TimestampUtc });

            entity.HasOne(e => e.Monitor)
                .WithMany()
                .HasForeignKey(e => e.MonitorId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Monitoring: Traffic monitor config
        modelBuilder.Entity<TrafficMonitorConfig>(entity =>
        {
            entity.HasIndex(e => e.Enabled);
            entity.HasIndex(e => e.UpdatedAt);
            entity.HasIndex(e => e.InterfaceName);
        });

        // Monitoring: Traffic samples
        modelBuilder.Entity<TrafficSample>(entity =>
        {
            entity.HasIndex(e => e.TimestampUtc);
            entity.HasIndex(e => e.InterfaceName);
            entity.HasIndex(e => new { e.InterfaceName, e.TimestampUtc });
        });

        // Enhancements: Alerting
        modelBuilder.Entity<AlertRule>(entity =>
        {
            entity.HasIndex(e => e.Enabled);
            entity.HasIndex(e => e.Scope);
            entity.HasIndex(e => e.NodeId);
            entity.HasIndex(e => e.UpdatedAt);

            entity.HasOne(e => e.Node)
                .WithMany(n => n.AlertRules)
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<AlertEvent>(entity =>
        {
            entity.HasIndex(e => e.AlertRuleId);
            entity.HasIndex(e => e.NodeId);
            entity.HasIndex(e => e.Status);
            entity.HasIndex(e => e.StartedAt);
            entity.HasIndex(e => new { e.AlertRuleId, e.Status, e.StartedAt });

            entity.HasOne(e => e.AlertRule)
                .WithMany(r => r.Events)
                .HasForeignKey(e => e.AlertRuleId)
                .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(e => e.Node)
                .WithMany(n => n.AlertEvents)
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Enhancements: Scripts
        modelBuilder.Entity<Script>(entity =>
        {
            entity.HasIndex(e => e.Name).IsUnique();
            entity.HasIndex(e => e.UpdatedAt);
        });

        modelBuilder.Entity<ScriptRun>(entity =>
        {
            entity.HasIndex(e => e.NodeId);
            entity.HasIndex(e => e.ScriptId);
            entity.HasIndex(e => e.Status);
            entity.HasIndex(e => e.CreatedAt);
            entity.HasIndex(e => new { e.NodeId, e.CreatedAt });

            entity.HasOne(e => e.Script)
                .WithMany(s => s.Runs)
                .HasForeignKey(e => e.ScriptId)
                .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(e => e.Node)
                .WithMany(n => n.ScriptRuns)
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Enhancements: Log policies
        modelBuilder.Entity<LogViewerPolicy>(entity =>
        {
            entity.HasIndex(e => e.NodeId);
            entity.HasIndex(e => new { e.NodeId, e.Path }).IsUnique();
            entity.HasIndex(e => new { e.NodeId, e.DisplayName });

            entity.HasOne(e => e.Node)
                .WithMany(n => n.LogViewerPolicies)
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Enhancements: Terminal sessions
        modelBuilder.Entity<TerminalSession>(entity =>
        {
            entity.HasIndex(e => e.NodeId);
            entity.HasIndex(e => e.ExpiresAt);
            entity.HasIndex(e => e.Status);
            entity.HasIndex(e => new { e.NodeId, e.CreatedAt });

            entity.HasOne(e => e.Node)
                .WithMany(n => n.TerminalSessions)
                .HasForeignKey(e => e.NodeId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Network tool execution history
        modelBuilder.Entity<NetworkToolHistoryEntry>(entity =>
        {
            entity.HasIndex(e => e.TimestampUtc);
            entity.HasIndex(e => e.ToolType);
            entity.HasIndex(e => new { e.ToolType, e.TimestampUtc });

            // Store as jsonb for efficient queryability
            entity.Property(e => e.InputJson).HasColumnType("jsonb");
            entity.Property(e => e.ResultJson).HasColumnType("jsonb");
        });
    }
}
