// <auto-generated />
using System;
using ManLab.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ManLab.Server.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260124182611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ManLab.Server.Data.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("CommandId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("HttpPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("Hub")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("HubMethod")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SpanId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool?>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.HasIndex("EventName");

                    b.HasIndex("Kind");

                    b.HasIndex("NodeId");

                    b.HasIndex("Success");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.CommandQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CommandType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DispatchAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastDispatchAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OutputLog")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NodeId");

                    b.HasIndex("Status");

                    b.HasIndex("NodeId", "CreatedAt");

                    b.HasIndex("NodeId", "CommandType", "Status", "CreatedAt");

                    b.ToTable("CommandQueue");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.AlertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("NodeId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("AlertRuleId", "Status", "StartedAt");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("NodeId");

                    b.HasIndex("Scope");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.FileBrowserPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MaxBytesPerRead")
                        .HasColumnType("integer");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("FileBrowserPolicies");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.GpuSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("GpuIndex")
                        .HasColumnType("integer");

                    b.Property<long?>("MemoryTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemoryUsedBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<float?>("TemperatureC")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("UtilizationPercent")
                        .HasColumnType("real");

                    b.Property<int>("Vendor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("NodeId", "Timestamp");

                    b.HasIndex("NodeId", "GpuIndex", "Timestamp");

                    b.HasIndex("NodeId", "Timestamp", "GpuIndex");

                    b.ToTable("GpuSnapshots");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.HttpMonitorCheck", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool?>("KeywordMatched")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<int?>("SslDaysRemaining")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id", "TimestampUtc");

                    b.HasIndex("MonitorId");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("MonitorId", "TimestampUtc");

                    b.HasIndex("MonitorId", "Success", "TimestampUtc");

                    b.ToTable("HttpMonitorChecks");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.HttpMonitorConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyContains")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("ExpectedStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastRunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Method")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Url");

                    b.ToTable("HttpMonitorConfigs");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.LogViewerPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MaxBytesPerRequest")
                        .HasColumnType("integer");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("NodeId", "DisplayName");

                    b.HasIndex("NodeId", "Path")
                        .IsUnique();

                    b.ToTable("LogViewerPolicies");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.ScheduledNetworkToolConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastRunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Target")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("ToolType");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("ToolType", "Enabled");

                    b.ToTable("ScheduledNetworkToolConfigs", (string)null);
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.Script", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Shell")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.ScriptRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ScriptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StderrTail")
                        .HasColumnType("text");

                    b.Property<string>("StdoutTail")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NodeId");

                    b.HasIndex("ScriptId");

                    b.HasIndex("Status");

                    b.HasIndex("NodeId", "CreatedAt");

                    b.ToTable("ScriptRuns");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.ServiceMonitorConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("NodeId", "ServiceName")
                        .IsUnique();

                    b.ToTable("ServiceMonitorConfigs");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.ServiceStatusSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("NodeId", "Timestamp");

                    b.HasIndex("NodeId", "ServiceName", "Timestamp");

                    b.HasIndex("NodeId", "Timestamp", "ServiceName");

                    b.ToTable("ServiceStatusSnapshots");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.SmartDriveSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PowerOnHours")
                        .HasColumnType("integer");

                    b.Property<string>("Raw")
                        .HasColumnType("jsonb");

                    b.Property<float?>("TemperatureC")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("NodeId", "Timestamp");

                    b.HasIndex("NodeId", "Device", "Timestamp");

                    b.HasIndex("NodeId", "Timestamp", "Device");

                    b.ToTable("SmartDriveSnapshots");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.TerminalSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("NodeId");

                    b.HasIndex("Status");

                    b.HasIndex("NodeId", "CreatedAt");

                    b.ToTable("TerminalSessions");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.TrafficMonitorConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("InterfaceName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastRunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("InterfaceName");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("TrafficMonitorConfigs");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.TrafficSample", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InterfaceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("RxBytesPerSec")
                        .HasColumnType("bigint");

                    b.Property<long?>("RxErrors")
                        .HasColumnType("bigint");

                    b.Property<long?>("SpeedBps")
                        .HasColumnType("bigint");

                    b.Property<long?>("TxBytesPerSec")
                        .HasColumnType("bigint");

                    b.Property<long?>("TxErrors")
                        .HasColumnType("bigint");

                    b.Property<float?>("UtilizationPercent")
                        .HasColumnType("real");

                    b.HasKey("Id", "TimestampUtc");

                    b.HasIndex("InterfaceName");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("InterfaceName", "TimestampUtc");

                    b.ToTable("TrafficSamples");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.UpsSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Backend")
                        .HasColumnType("integer");

                    b.Property<float?>("BatteryPercent")
                        .HasColumnType("real");

                    b.Property<int?>("EstimatedRuntimeSeconds")
                        .HasColumnType("integer");

                    b.Property<float?>("LoadPercent")
                        .HasColumnType("real");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("OnBattery")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("NodeId", "Timestamp");

                    b.ToTable("UpsSnapshots");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.EnrollmentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("MachineId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsedAt");

                    b.ToTable("EnrollmentTokens");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.NetworkToolHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("TagsJson")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Target")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("ToolType");

                    b.HasIndex("ToolType", "TimestampUtc");

                    b.ToTable("NetworkToolHistory");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AuthKeyHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("CapabilitiesJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ErrorAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("OS")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryInterface")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthKeyHash");

                    b.HasIndex("Hostname");

                    b.HasIndex("LastSeen");

                    b.HasIndex("Status");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.NodeSetting", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("NodeId", "Key");

                    b.HasIndex("NodeId");

                    b.ToTable("NodeSettings");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.OnboardingMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedPrivateKeyPassphrase")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("EncryptedPrivateKeyPem")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<string>("EncryptedSshPassword")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("EncryptedSudoPassword")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("ForceInstall")
                        .HasColumnType("boolean");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HostKeyFingerprint")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastError")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid?>("LinkedNodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<bool>("RunAsRoot")
                        .HasColumnType("boolean");

                    b.Property<string>("ServerBaseUrlOverride")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("TrustHostKey")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Host");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("OnboardingMachines");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.SshAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Actor")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CpuArch")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Host")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HostKeyFingerprint")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("OsDistro")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OsFamily")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("Port")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Host");

                    b.HasIndex("MachineId");

                    b.HasIndex("Success");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("SshAuditEvents");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.TelemetrySnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float?>("AgentCpuPercent")
                        .HasColumnType("real");

                    b.Property<long?>("AgentGcHeapBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("AgentMemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("AgentThreadCount")
                        .HasColumnType("integer");

                    b.Property<string>("ApmJson")
                        .HasColumnType("text");

                    b.Property<float>("CpuUsage")
                        .HasColumnType("real");

                    b.Property<float>("DiskUsage")
                        .HasColumnType("real");

                    b.Property<string>("EnhancedGpuJson")
                        .HasColumnType("text");

                    b.Property<string>("EnhancedNetworkJson")
                        .HasColumnType("text");

                    b.Property<long?>("NetRxBytesPerSec")
                        .HasColumnType("bigint");

                    b.Property<long?>("NetTxBytesPerSec")
                        .HasColumnType("bigint");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<float?>("PingPacketLossPercent")
                        .HasColumnType("real");

                    b.Property<float?>("PingRttMs")
                        .HasColumnType("real");

                    b.Property<string>("PingTarget")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<float>("RamUsage")
                        .HasColumnType("real");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("NodeId", "Timestamp");

                    b.ToTable("TelemetrySnapshots");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.CommandQueueItem", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany("Commands")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.AlertEvent", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Enhancements.AlertRule", "AlertRule")
                        .WithMany("Events")
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany("AlertEvents")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AlertRule");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.AlertRule", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany("AlertRules")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.FileBrowserPolicy", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany("FileBrowserPolicies")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.GpuSnapshot", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany("GpuSnapshots")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.HttpMonitorCheck", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Enhancements.HttpMonitorConfig", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.LogViewerPolicy", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany("LogViewerPolicies")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.ScriptRun", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany("ScriptRuns")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManLab.Server.Data.Entities.Enhancements.Script", "Script")
                        .WithMany("Runs")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.ServiceMonitorConfig", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany("ServiceMonitorConfigs")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.ServiceStatusSnapshot", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany("ServiceStatusSnapshots")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.SmartDriveSnapshot", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany("SmartDriveSnapshots")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.TerminalSession", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany("TerminalSessions")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.UpsSnapshot", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany("UpsSnapshots")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.NodeSetting", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.TelemetrySnapshot", b =>
                {
                    b.HasOne("ManLab.Server.Data.Entities.Node", "Node")
                        .WithMany("TelemetrySnapshots")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.AlertRule", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Enhancements.Script", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("ManLab.Server.Data.Entities.Node", b =>
                {
                    b.Navigation("AlertEvents");

                    b.Navigation("AlertRules");

                    b.Navigation("Commands");

                    b.Navigation("FileBrowserPolicies");

                    b.Navigation("GpuSnapshots");

                    b.Navigation("LogViewerPolicies");

                    b.Navigation("ScriptRuns");

                    b.Navigation("ServiceMonitorConfigs");

                    b.Navigation("ServiceStatusSnapshots");

                    b.Navigation("SmartDriveSnapshots");

                    b.Navigation("TelemetrySnapshots");

                    b.Navigation("TerminalSessions");

                    b.Navigation("UpsSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
